# Generated by Django 4.2.3 on 2023-10-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_subject_rename_student_age_student_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
