# Generated by Django 4.2.3 on 2023-10-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_studentid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
