# Generated by Django 4.2.3 on 2023-09-09 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
